import React from 'react';
import { motion } from 'motion/react';
import { Gavel, Mail, Scale, FileText, ChevronLeft, AlertCircle } from 'lucide-react';
import { useNavigate, Link } from 'react-router-dom';

export default function TermsOfService() {
  const navigate = useNavigate();

  React.useEffect(() => {
    document.title = "AerovaX | Terms of Service";
  }, []);

  return (
    <div className="min-h-screen bg-slate-50 font-sans text-slate-900">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="bg-brand-indigo/10 p-2 rounded-lg text-brand-indigo">
              <Gavel className="h-5 w-5" />
            </div>
            <span className="font-bold text-lg tracking-tight">AerovaX Terms of Service</span>
          </div>
          <button 
            onClick={() => navigate(-1)}
            className="flex items-center gap-2 text-slate-500 hover:text-brand-indigo transition-colors text-sm font-medium"
          >
            <ChevronLeft className="h-4 w-4" />
            Back
          </button>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-12 lg:py-20">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="bg-white border border-slate-200 rounded-3xl shadow-sm overflow-hidden"
        >
          <div className="p-8 lg:p-12">
            <h1 className="text-3xl lg:text-4xl font-bold text-slate-900 mb-8 tracking-tight">
              Terms of Service
            </h1>

            <div className="prose prose-slate max-w-none space-y-8">
              <section>
                <p className="text-lg text-slate-600 leading-relaxed">
                  By using the AerovaX School Management System, you agree to comply with the following terms and guidelines. These terms govern the relationship between Labbaik English School and users of the platform (parents, staff, and administrators).
                </p>
              </section>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <section className="bg-slate-50 rounded-2xl p-6 border border-slate-100">
                  <div className="flex items-center gap-3 mb-4">
                    <Scale className="h-5 w-5 text-brand-indigo" />
                    <h2 className="text-lg font-bold text-slate-800 m-0">Acceptable Use</h2>
                  </div>
                  <p className="text-sm text-slate-600 leading-relaxed">
                    Users must use the platform exclusively for educational and school-related communication purposes. Harassment, spamming, or any attempt to compromise system security is strictly prohibited.
                  </p>
                </section>

                <section className="bg-slate-50 rounded-2xl p-6 border border-slate-100">
                  <div className="flex items-center gap-3 mb-4">
                    <AlertCircle className="h-5 w-5 text-brand-indigo" />
                    <h2 className="text-lg font-bold text-slate-800 m-0">AI Disclaimer</h2>
                  </div>
                  <p className="text-sm text-slate-600 leading-relaxed">
                    Some responses via WhatsApp may be generated by AI. While we strive for accuracy, AI replies should be treated as guidance. Always consult the school office for official confirmations regarding fees or critical dates.
                  </p>
                </section>
              </div>

              <section className="space-y-4">
                <h2 className="text-xl font-bold text-slate-800 tracking-tight">User Rights & Responsibilities</h2>
                <div className="space-y-4">
                  <div className="flex gap-4">
                    <div className="h-6 w-6 rounded-full bg-brand-indigo/10 flex items-center justify-center text-brand-indigo text-xs font-bold shrink-0 mt-1">1</div>
                    <p className="text-slate-600 m-0">
                      <span className="font-bold text-slate-800">Privacy Compliance:</span> Users agree to the collection and processing of data as outlined in our <Link to="/privacy-policy" className="text-brand-indigo hover:underline">Privacy Policy</Link>.
                    </p>
                  </div>
                  <div className="flex gap-4">
                    <div className="h-6 w-6 rounded-full bg-brand-indigo/10 flex items-center justify-center text-brand-indigo text-xs font-bold shrink-0 mt-1">2</div>
                    <p className="text-slate-600 m-0">
                      <span className="font-bold text-slate-800">Account Security:</span> You are responsible for maintaining the confidentiality of your access to the platform and notifications received.
                    </p>
                  </div>
                  <div className="flex gap-4">
                    <div className="h-6 w-6 rounded-full bg-brand-indigo/10 flex items-center justify-center text-brand-indigo text-xs font-bold shrink-0 mt-1">3</div>
                    <p className="text-slate-600 m-0">
                      <span className="font-bold text-slate-800">Operational Rights:</span> Labbaik English School reserves the right to suspend or terminate access to the platform for users found in violation of these terms.
                    </p>
                  </div>
                </div>
              </section>

              <section className="p-6 bg-amber-50 border border-amber-100 rounded-2xl">
                <h3 className="text-amber-800 font-bold mb-2">Limitation of Liability</h3>
                <p className="text-sm text-amber-700 m-0 leading-relaxed">
                  Labbaik English School and the AerovaX platform developers provide this service "as is" without any express or implied warranties. We are not liable for any communication delays or inaccuracies caused by technical failures or third-party service interruptions (e.g., Meta, Firebase, OpenRouter).
                </p>
              </section>

              <section className="mt-12 p-8 bg-slate-900 rounded-2xl text-white">
                <div className="flex items-center gap-3 mb-4">
                  <Mail className="h-5 w-5 text-brand-cyan" />
                  <h2 className="text-xl font-bold text-white tracking-tight m-0">Inquiries</h2>
                </div>
                <p className="text-slate-300 mb-6">
                  For any questions regarding these Terms of Service, please contact Labbaik English School administration.
                </p>
                <div className="space-y-1 pt-4 border-t border-white/10">
                  <p className="font-bold text-lg text-white m-0">Labbaik English School</p>
                  <p className="text-brand-cyan font-medium m-0">labbaikenglishschool8@gmail.com</p>
                </div>
              </section>
            </div>
          </div>
        </motion.div>

        <footer className="mt-12 flex flex-col md:flex-row items-center justify-center gap-6 text-slate-400 text-sm">
          <Link to="/privacy-policy" className="hover:text-brand-indigo transition-colors">Privacy Policy</Link>
          <Link to="/data-deletion" className="hover:text-brand-indigo transition-colors">Data Deletion</Link>
          <p>© {new Date().getFullYear()} AerovaX. All rights reserved.</p>
        </footer>
      </main>
    </div>
  );
}
